aubaine_platform_home:
    path:      /admin/{page}
    defaults:
        _controller: AubainePlatformBundle:Aubaine:index
        page:        1
    requirements:
        page: \d*

aubaine_platform_view:
    path:      /admin/aubaine/{id}
    defaults:
        _controller: AubainePlatformBundle:Aubaine:view

aubaine_platform_add:
    path:      /admin/add
    defaults:
        _controller: AubainePlatformBundle:Aubaine:add

aubaine_platform_add_multiple:
    path:      /admin/add_multiple
    defaults:
        _controller: AubainePlatformBundle:Aubaine:addMultiple

aubaine_platform_edit:
    path:      /admin/edit/{id}
    defaults:
        _controller: AubainePlatformBundle:Aubaine:edit

aubaine_platform_delete:
    path:      /admin/delete/{id}
    defaults:
        _controller: AubainePlatformBundle:Aubaine:delete

aubaine_platform_delete_aubaine:
    path:      deleteAubaine/{id}
    defaults:
        _controller: AubainePlatformBundle:Aubaine:deleteAubaine

aubaine_platform_populate:
    path:      /admin/populate
    defaults:
        _controller: AubainePlatformBundle:Aubaine:populate

aubaine_platform_my_aubaines:
    path:      /agenda/{week}
    defaults:
        _controller: AubainePlatformBundle:Aubaine:my_aubaines

 # Ajax
aubaine_platform_ajax_add_aubaine:
    path:  /ajax_add_aubaine
    defaults: { _controller: AubainePlatformBundle:Aubaine:ajax_add_aubaine }
    requirements:
      _method: POST

aubaine_platform_ajax_add_aubaine_multiple:
    path:  /ajax_add_aubaine_multiple
    defaults: { _controller: AubainePlatformBundle:Aubaine:ajax_add_aubaine_multiple }
    requirements:
      _method: POST

aubaine_platform_load_marker:
    path:      /load_marker
    defaults:
        _controller: AubainePlatformBundle:Aubaine:load_marker
    requirements:
        _method: POST