aubaine_platform_home:
    path:      /admin/{page}
    defaults:
        _controller: AubainePlatformBundle:Aubaine:index
        page:        1
    requirements:
        page: \d*

aubaine_platform_view:
    path:      /admin/aubaine/{id}
    defaults:
        _controller: AubainePlatformBundle:Aubaine:view

aubaine_platform_public_view:
    path:      /aubaine/{id}
    defaults:
        _controller: AubainePlatformBundle:Aubaine:publicView

aubaine_platform_add:
    path:      /admin/add
    defaults:
        _controller: AubainePlatformBundle:Aubaine:add

aubaine_platform_edit:
    path:      /admin/edit/{id}
    defaults:
        _controller: AubainePlatformBundle:Aubaine:edit

aubaine_platform_delete:
    path:      /admin/delete/{id}
    defaults:
        _controller: AubainePlatformBundle:Aubaine:delete

aubaine_platform_delete_aubaine:
    path:      deleteAubaine/{id}
    defaults:
        _controller: AubainePlatformBundle:Aubaine:deleteAubaine

aubaine_platform_my_aubaines:
    path:      /agenda
    defaults:
        _controller: AubainePlatformBundle:Aubaine:my_aubaines