fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /security

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /demo/secured/connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /demo/secured/connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /demo/secured/login

facebook_login:
    path: /demo/secured/login-facebook

google_login:
    path: /demo/secured/login-google

aubaine_core:
    resource: "@AubaineCoreBundle/Resources/config/routing.yml"
    prefix:   /

aubaine_deal:
    resource: "@AubaineDealBundle/Resources/config/routing.yml"
    prefix:   /deal

aubaine_event:
    resource: "@AubaineEventBundle/Resources/config/routing.yml"
    prefix:   /event

aubaine_place:
    resource: "@AubainePlaceBundle/Resources/config/routing.yml"
    prefix:   /place

aubaine_platform:
    resource: "@AubainePlatformBundle/Resources/config/routing.yml"
    prefix:   /aubaines

aubaine_user:
    resource: "@AubaineUserBundle/Resources/config/routing.yml"
    prefix:   /membre

