# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.form.registration:
        class: Aubaine\UserBundle\Form\Type\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
    app.form.profile:
        class: Aubaine\UserBundle\Form\Type\ProfileType
        tags:
            - { name: form.type, alias: app_user_profile }
    my.oauth_aware.user_provider.service:
        class: HWI\Bundle\OAuthBundle\Security\Core\User\FOSUBUserProvider
        arguments:
            - '@fos_user.user_manager'
            - [{facebook: facebookid, gplus: gplusUid}]
    my.custom.user_provider:
        class:        Aubaine\UserBundle\Document\MyFOSUBUserProvider
        arguments: ['@fos_user.user_manager', { facebook: facebookid }]
    app_core.facebook:
        class: Aubaine\CoreBundle\Facebook\FacebookService
        arguments: ["%app_id%","%app_secret%","%page_id%","%token%"]