<?php

namespace Aubaine\PlatformBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * AubaineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AubaineRepository extends DocumentRepository
{
	public function findAllOrderedByName()
    {
        return $this->createQueryBuilder()
            ->sort('dateCreated', 'DESC')
            ->getQuery()
            ->execute();
    }
    public function getAubaines($page, $nbPerPage)
	{
		return $this->createQueryBuilder()
		  ->sort('date', 'DESC')
		  ->limit($nbPerPage)
		  ->skip(($page-1) * $nbPerPage)
		  ->getQuery()
          ->execute();
		;
	}
    public function getAubainesByAuthor($userId, $month_first_day, $month_last_day)
	{
		return $this->createQueryBuilder()
			->field('date')->lte($month_last_day)
			->field('date')->gte($month_first_day)
			->field('idAuthor')->equals($userId)
			->getQuery()
			->execute();
		;
	}
    public function getCurrentAubaineByAuthor($userId, $date)
	{
		return $this->createQueryBuilder()
			->field('date')->equals($date)
			->field('idAuthor')->equals($userId)
			->getQuery()
			->getSingleResult()
		;
	}
}
