aubaine_core_homepage:
    path:     /
    defaults: { _controller: AubaineCoreBundle:Home:index }
aubaine_core_map:
    path:     /carte
    defaults: { _controller: AubaineCoreBundle:Home:map }
aubaine_core_live:
    path:     /live
    defaults: { _controller: AubaineCoreBundle:Home:live }
aubaine_core_concept:
    path:     /concept
    defaults: { _controller: AubaineCoreBundle:Home:concept }
aubaine_core_partner:
    path:     /devenir-partenaire
    defaults: { _controller: AubaineCoreBundle:Home:partner }
aubaine_core_cgu:
    path:     /cgu
    defaults: { _controller: AubaineCoreBundle:Home:cgu }
aubaine_core_ajax_newsletter:
    path:     /ajax-newsletter
    defaults: { _controller: AubaineCoreBundle:Home:ajax_newsletter }
