aubaine_core_homepage:
    path:     /
    defaults: { _controller: AubaineCoreBundle:Home:index }
aubaine_core_preregister:
    path:     /preregister
    defaults: { _controller: AubaineCoreBundle:Home:preregister }
aubaine_core_activate:
    path:     /activer-mon-compte
    defaults: { _controller: AubaineCoreBundle:Home:activate }
aubaine_core_map:
    path:     /carte/{city}
    defaults: { _controller: AubaineCoreBundle:Home:map, city: toulouse}
aubaine_core_live:
    path:     /recherche/{city}/{category}/{search}
    defaults: { _controller: AubaineCoreBundle:Home:live, city: toulouse , category: all , search: all }
aubaine_core_card:
    path:     /carte-aubaine
    defaults: { _controller: AubaineCoreBundle:Home:card }
aubaine_core_concept:
    path:     /concept
    defaults: { _controller: AubaineCoreBundle:Home:concept }
aubaine_core_partner:
    path:     /devenir-partenaire
    defaults: { _controller: AubaineCoreBundle:Home:partner }
aubaine_core_cgu:
    path:     /cgu
    defaults: { _controller: AubaineCoreBundle:Home:cgu }
aubaine_core_ajax_futuremember:
    path:     /ajax-futuremember
    defaults: { _controller: AubaineCoreBundle:Home:ajax_futuremember }
aubaine_core_ajax_newsletter:
    path:     /ajax-newsletter
    defaults: { _controller: AubaineCoreBundle:Home:ajax_newsletter }
aubaine_core_search:
    path:     /search
    defaults: { _controller: AubaineCoreBundle:Home:search }
aubaine_core_subscription:
    path:     /subscription
    defaults: { _controller: AubaineCoreBundle:Home:subscription }
aubaine_core_email:
    path:     /email
    defaults: { _controller: AubaineCoreBundle:Home:email }
aubaine_core_places:
    path:      /lieux/{city}/{category}/{search}
    defaults: { _controller: AubaineCoreBundle:Home:places, city: toulouse , category: all , search: all }
aubaine_core_facebook:
    path:      /facebook
    defaults: { _controller: AubaineCoreBundle:Home:facebook }